### PR TITLE
Add CHD file support

### LINKED ISSUE #2584: [Request]Add CHD format support for compressed disc
Hello there, love the project, can we get some CHD love for the pcsx2 as a compressed disk format?

CHD or "Compressed Hunks of Data" - it's a MAME format for storing disk images.

With libchdr from @rtissera this should be doable like the new retroarch cores do
https://github.com/rtissera/libchdr

Some of the benefits the CHD support have:
.-lossless compression
.-15-18% better compression than pbp (this makes a bin cue uncompressed collection almost half its size)
.-its a streamable format, it doesnt need to decompress, just play
.-its increadibly easy to convert entire folders filled with uncompressed psx games with a batch file
.-every disc turns into just one file
.-supports redbook audio in flac compression
.-its becoming the defacto standard for libretro cores with support in mame, saturn, pcengine/turbografx, segacd/megacd, psx beetle and future support for dreamcast (in a few days)

Twice the fun, same space

Thanks in advance
Best regards

### PR DESCRIPTION
**Pull request by siddhartha77**
Okay, here are all my changes. You should be able to merge it easily and update https://github.com/PCSX2/pcsx2/pull/4045 to finally close https://github.com/PCSX2/pcsx2/issues/2584. It will compile on Ubuntu 20.04 and MSVC 2019 Community. Most of the changes were with the directory structure, CMAKE files, and the MSVC files. I also added [large file support](https://github.com/rtissera/libchdr/pull/43) for >2GB CHDs.

One thing we should eventually do is update it to use xz instead of lzma, but that will take a ton of work.

**Thanks for all your hard work too!**

### CODE REVIEW

**Comment by siddhartha77** [comment]
It would be prudent to check out [this PR](https://github.com/rtissera/libchdr/pull/43) and the resulting issues with large file support across platforms.

**Comment by 0x90shell** [comment]
@siddhartha77 Looks like libchdr maintainer wants you to make some edits to merge the changes upstream to libretro

**Comment by BakedCrossiant** [comment]
@siddhartha77 any updates?

**Comment by rtissera** [comment]
libchdr https://github.com/rtissera/libchdr/pull/42 by @SleepyMan was finally merged.

**Comment by tempt187** [comment]
Any chance on this getting merged soon? There are a lot of files greater than 2GB in CHD format left to support.

**Comment by rtissera** [comment]
I don't get it.
CHD support was merged in PCSX2 upstream check https://github.com/PCSX2/pcsx2/pull/4314

**Comment by tempt187** [comment]
> I don't get it.
> CHD support was merged in PCSX2 upstream check [PCSX2#4314](https://github.com/PCSX2/pcsx2/pull/4314)

It does work, but it appears this request will fix the > 2GB CHD? I'm getting the following errors on boot for any CHD compressed PS2 game greater than 2GB. Every CHD < 2GB works fine though.

isoFile error: Block index is past the end of file! (1502786 >= 1121296).
isoFile error: Block index is past the end of file! (1502787 >= 1121296)

and either the emulator crashes or the game never starts

**Comment by Dio141** [comment]
> 
> 
> > I don't get it.
> > CHD support was merged in PCSX2 upstream check [PCSX2#4314](https://github.com/PCSX2/pcsx2/pull/4314)
> 
> It does work, but it appears this request will fix the > 2GB CHD? I'm getting the following errors on boot for any CHD compressed PS2 game greater than 2GB. Every CHD < 2GB works fine though.
> 
> isoFile error: Block index is past the end of file! (1502786 >= 1121296).
> isoFile error: Block index is past the end of file! (1502787 >= 1121296)
> 
> and either the emulator crashes or the game never starts

i just tried a 2.5gb CHD, and it booted just fine here.

**Comment by siddhartha77** [comment]
> > I don't get it.
> > CHD support was merged in PCSX2 upstream check [PCSX2#4314](https://github.com/PCSX2/pcsx2/pull/4314)
> 
> It does work, but it appears this request will fix the > 2GB CHD? I'm getting the following errors on boot for any CHD compressed PS2 game greater than 2GB. Every CHD < 2GB works fine though.
> 
> isoFile error: Block index is past the end of file! (1502786 >= 1121296).
> isoFile error: Block index is past the end of file! (1502787 >= 1121296)
> 
> and either the emulator crashes or the game never starts

Sorry, I've been offline for so long. Life.

Can I confirm your operating system and which version of PCSX2 you are compiling?

**Comment by siddhartha77** [comment]
I have just tried the [latest nightly Windows build](https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.7.0-dev-1211-g290183040&platform=windows-x86) and compiled the latest Linux version (the same @ [2901830](https://github.com/PCSX2/pcsx2/commit/290183040ff6ae873a44c69e91125fc714bd5ad3)) on Ubuntu 20.04. Both were able to boot into a God of War CHD that is over 6.8 GB.

Thanks to everyone, especially @rtissera for all their hard work.

**Pull request closed without merging**
